<?php
/**
 * editavatar
 *
 * @copyright Copyright © 2021 Khanh. All rights reserved.
 * @author    khanhthanhvh@gmail.com
 */
?>
<div class="field choice">
    <input type="checkbox" name="change_avatar" id="change-avatar" data-role="change-avatar" value="1"
           title="Avatar" class="checkbox" />
    <label class="label" for="change-avatar">
        <span>Change Avatar</span>
    </label>
</div>
