<?php
/**
 * editavatar
 *
 * @copyright Copyright © 2021 Khanh. All rights reserved.
 * @author    khanhthanhvh@gmail.com
 */
/** @var \Magenest\Customer\Block\Account\Dashboard\Info $block */
?>

<div class="field required" data-container="change-avatar">
    <label class="label" for="avatar"><span>Avatar</span></label>
    <div class="control">
        <input type="file" name="Avatar" >
    </div>
</div>
