<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */


/** @var \Magenest\Report\Block\Content1st\Content $block */
/** @var $escaper \Magento\Framework\Escaper */
?>

<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Magenest_Report::css/style6.css')?>">
<style>
    .table{
        font-size: 20px;
        font-weight: 15;

    }

</style>
<div style="text-align: center">
    <h1><b style="font-size: 40px">Module Number</b></h1>
</div>
<table class="table table-striped">
    <tr>
        <th scope="col">Numbers</th>
        <td><?= $block->getCountModule() ?></td>
    </tr>
</table>








