<?php
/**
 * customer
 *
 * @copyright Copyright © 2021 Khanh. All rights reserved.
 * @author    khanhthanhvh@gmail.com
 */
?>
<style>
    body {font-family: Arial, Helvetica, sans-serif;}
    * {box-sizing: border-box;}

    /* Button used to open the contact form - fixed at the bottom of the page */
    .open-button {
        background-color: #555;
        color: white;
        padding: 16px 20px;
        border: none;
        cursor: pointer;
        opacity: 0.8;
        position: fixed;
        bottom: 23px;
        right: 28px;
        width: 280px;
    }

    /* The popup form - hidden by default */
    .form-popup {
        display: none;
        position: fixed;
        bottom: 0;
        right: 15px;
        border: 3px solid #f1f1f1;
        z-index: 9;
    }

    /* Add styles to the form container */
    .form-container {
        max-width: 300px;
        padding: 10px;
        background-color: white;
    }

    /* Full-width input fields */
    .form-container input[type=text], .form-container input[type=password] {
        width: 100%;
        padding: 15px;
        margin: 5px 0 22px 0;
        border: none;
        background: #f1f1f1;
    }

    /* When the inputs get focus, do something */
    .form-container input[type=text]:focus, .form-container input[type=password]:focus {
        background-color: #ddd;
        outline: none;
    }

    /* Set a style for the submit/login button */
    .form-container .btn {
        background-color: #04AA6D;
        color: white;
        padding: 16px 20px;
        border: none;
        cursor: pointer;
        width: 100%;
        margin-bottom:10px;
        opacity: 0.8;
    }

    /* Add a red background color to the cancel button */
    .form-container .cancel {
        background-color: red;
    }

    /* Add some hover effects to buttons */
    .form-container .btn:hover, .open-button:hover {
        opacity: 1;
    }
</style>


<button class="open-button" onclick="openForm()">Khuyến mãi</button>

<div class="form-popup" id="myForm">
    <div class="form-container">
        <label>Chương trình khuyến mãi</label>

        <label for="email"><b>Email</b></label>

        <label for="psw"><b>Password</b></label>


        <button type="button" class="btn cancel" onclick="closeForm()">Close</button>
    </div>
</div>

<h1>Modal Test Page</h1>

<table>
    <tr>
        <th>
            <!-- Button trigger modal -->
            <button type="button" id="button">
                Open Model
            </button>
        </th>
        <th>
            <button onclick="alert()">Open</button>
        </th>
        <th>
            <button>Open Model</button>
        </th>
    </tr>

</table>

<!-------------------------- Modal ------------------>
<div id="modal">
    <div class="modal-body-content">
        <div style="height: 450px; background: #00ff00; align-items: center;justify-content: center;display: flex;">
            <div style="width: 400px; height: 200px; background: #FFFFFF;align-items: center;justify-content: center;display: flex;">
                <div style="text-align: center">
                    <input type="text" placeholder="UserName" style="width: 300px;"> <div style="height: 10px"></div>
                    <input type="password" placeholder="Password" style="width: 300px"> <div style="height: 10px"></div>
                    <button type="button" class="btn btn-submit" style="width: 300px; " >Login</button> <div style="height: 10px"></div>
                    <p>Not registered? <a href="" style="color: #3c763d">Create an account</a></p>
                </div>

            </div>
        </div>

    </div>
</div>

<script>
    function myFunction() {
        require([
            'Magento_Ui/js/modal/alert'
            'jquery'
        ], function (alert, $) { // Variable that represents the `alert` function

            alert({
                title: $.mage.__('Some title'),
                content: $.mage.__('Some content'),
                actions: {
                    always: function () {
                    }
                }
            });

        });
    }
</script>

<script>
    require([
        "jquery", "Magento_Ui/js/modal/modal"
    ],function($, modal) {
        var options = {
            type: 'popup',
            responsive: true,
            title: 'Login Modal',
            buttons: []
        };
        var popup = modal(options, $('#modal'));
        // $(document).readOnly(function (){
        //     $('#modal').modal('widget');
        // });
        $("#button").click(function() {
            // $('#modal').modal('openModal');
            $('#modal').modal('_show');
        });
    });
</script>


<script>
    function openForm() {
        document.getElementById("myForm").style.display = "block";
    }

    function closeForm() {
        document.getElementById("myForm").style.display = "none";
    }
</script>



